### ISSUE TITLE
Can't build my iOS app using Kinesis at v2.3.5

### ISSUE THREAD

**Issue by nayutaya** [aws/aws-sdk-ios#316]
There is a problem with v2.3.5 and v2.3.4 of AWS SDK for iOS.
My iOS app uses Amazon Kinesis service.
That app can build with v2.3.2, but that can't build with v2.3.5 and v2.3.4.
maybe, v2.3.5 does not contain `AWSFirehoseService.h`.

My app's `Bridging-Header.h` has following lines.

```
#import <AWSKinesis/AWSKinesis.h>
```

and I got following error messages.

```
/Users/yuya/repo/xxx/xxx-Bridging-Header.h:7:9: note: while building module 'AWSKinesis' imported from /Users/yuya/repo/xxx/xxx-Bridging-Header.h:7:
#import <AWSKinesis/AWSKinesis.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/yuya/repo/xxx/aws-ios-sdk-2.3.5/AWSKinesis.framework/Headers/AWSKinesis.h"
        ^
/Users/yuya/repo/xxx/aws-ios-sdk-2.3.5/AWSKinesis.framework/Headers/AWSKinesis.h:20:9: note: in file included from /Users/yuya/repo/xxx/aws-ios-sdk-2.3.5/AWSKinesis.framework/Headers/AWSKinesis.h:20:
#import "AWSFirehose.h"
        ^
/Users/yuya/repo/xxx/aws-ios-sdk-2.3.5/AWSKinesis.framework/Headers/AWSFirehose.h:18:9: error: 'AWSFirehoseService.h' file not found
#import "AWSFirehoseService.h"
        ^
/Users/yuya/repo/xxx/xxx-Bridging-Header.h:7:9: error: could not build module 'AWSKinesis'
#import <AWSKinesis/AWSKinesis.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/yuya/repo/xxx/xxx-Bridging-Header.h'
```

My environment:

* OS: OS X El Capitan(10.11.3)
* Xcode: 7.2 (7C68)

**Comment by yosuke-matsuda** [comment]
Thank you for bringing the issue to our attention. The Firehose header files are not properly set to public in the project file, and it resulted in the missing headers. We will fix it in the next release. Meanwhile, you can grab the necessary headers from this GitHub repo and put it in the Headers folder of `AWSKinesis.framework`. Thanks.

**Comment by yosuke-matsuda** [comment]
We've updated the frameworks to include the Firehose header files. Could you download the framework and try again? Thanks.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. Please feel free to let us know if you continue encountering the error. Thanks.

**Comment by nayutaya** [comment]
I tried `aws-ios-sdk-2.3.6`.
That is completely working. Thank you very much!
